/*

Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 lambo.gltf 
Author: SDC PERFORMANCE™️ (https://sketchfab.com/Lambo_SC04)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/aventador-svj-katanatm-sdctm-x-blackdeath-3a180dd964ae47ff91f65011a4b9b7f7
Title: Aventador SVJ KATANA™️ - SDC™️ x BLACKDEATH
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Lambo(props) {
  const { nodes, materials } = useGLTF("/lambo.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group scale={100}>
          <mesh
            geometry={nodes.Object_22_Material_001_0.geometry}
            material={materials.Material_001}
          />
          <mesh
            geometry={nodes.Object_22_Material001_0.geometry}
            material={materials["Material.001"]}
          />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={95.874}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group rotation={[0.013, 0, -Math.PI]} scale={1.494}>
              <mesh
                geometry={nodes.Object_4_JANTE_0.geometry}
                material={materials.JANTE}
              />
              <mesh
                geometry={nodes.Object_5_plaquette_de_frein002_0.geometry}
                material={materials["plaquette_de_frein.002"]}
              />
              <mesh
                geometry={nodes.Object_6_visse002_0.geometry}
                material={materials["visse.002"]}
              />
              <mesh
                geometry={nodes.Object_7_CRBN_JANTE_0.geometry}
                material={materials.CRBN_JANTE}
              />
              <mesh
                geometry={nodes.Object_8_CARROSSERIE_0.geometry}
                material={materials.CARROSSERIE}
              />
              <mesh
                geometry={nodes.Object_9_Material008_0.geometry}
                material={materials["Material.008"]}
              />
              <mesh
                geometry={nodes.Object_9_Material008_0_1.geometry}
                material={materials["Material.008"]}
              />
              <mesh
                geometry={nodes.Object_10_Material008_0.geometry}
                material={materials["Material.008"]}
              />
              <mesh
                geometry={nodes.Object_11_JANTE_0.geometry}
                material={materials.JANTE}
              />
              <mesh
                geometry={nodes.Object_12_JANTE_0.geometry}
                material={materials.JANTE}
              />
              <mesh
                geometry={nodes.Object_13_pneu001_0.geometry}
                material={materials["pneu.001"]}
              />
              <mesh
                geometry={nodes.Object_13_pneu001_0_1.geometry}
                material={materials["pneu.001"]}
              />
              <mesh
                geometry={nodes.Object_14_pneu001_0.geometry}
                material={materials["pneu.001"]}
              />
              <mesh
                geometry={nodes.Object_15_pneu001_0.geometry}
                material={materials["pneu.001"]}
              />
              <mesh
                geometry={nodes.Object_16_pneu001_0.geometry}
                material={materials["pneu.001"]}
              />
              <mesh
                geometry={nodes.Object_17_PZEO001_0.geometry}
                material={materials["PZEO.001"]}
              />
              <mesh
                geometry={nodes.Object_18_Material049_0.geometry}
                material={materials["Material.049"]}
              />
            </group>
            <mesh
              geometry={nodes.Object_20_Undercarriage_0.geometry}
              material={materials.Undercarriage}
              position={[0, 0.127, 0.042]}
              rotation={[0.013, 0, -Math.PI]}
              scale={0.001}
            />
            <group
              position={[-0.002, 0.121, 0.037]}
              rotation={[0.013, 0, -Math.PI]}
              scale={0.001}
            >
              <mesh
                geometry={nodes.Object_24_GLS_MR_0.geometry}
                material={materials.GLS_MR}
              />
              <mesh
                geometry={nodes.Object_25_CARBONE_0.geometry}
                material={materials.CARBONE}
              />
              <mesh
                geometry={nodes.Object_26_MetalDark_0.geometry}
                material={materials.MetalDark}
              />
              <mesh
                geometry={nodes.Object_27_Chrome_0.geometry}
                material={materials.Chrome}
              />
              <mesh
                geometry={nodes.Object_28_GlassLights_0.geometry}
                material={materials.GlassLights}
              />
              <mesh
                geometry={nodes.Object_29_GlassRedLights_0.geometry}
                material={materials.GlassRedLights}
              />
              <mesh
                geometry={nodes.Object_30_GlassOrangeLights_0.geometry}
                material={materials.GlassOrangeLights}
              />
              <mesh
                geometry={nodes.Object_31_GlassWhite_0.geometry}
                material={materials.GlassWhite}
              />
              <mesh
                geometry={nodes.Object_32_Aluminum_0.geometry}
                material={materials.Aluminum}
              />
            </group>
            <group
              position={[0, 0.127, 0.041]}
              rotation={[0.013, 0, -Math.PI]}
              scale={0.001}
            >
              <mesh
                geometry={nodes.Object_34_CARBONE_0.geometry}
                material={materials.CARBONE}
              />
              <mesh
                geometry={nodes.Object_35_Chrome_0.geometry}
                material={materials.Chrome}
              />
              <mesh
                geometry={nodes.Object_36_HdLightsLens_0.geometry}
                material={materials.HdLightsLens}
              />
              <mesh
                geometry={nodes.Object_37_MetalExhaustTextured_0.geometry}
                material={materials.MetalExhaustTextured}
              />
              <mesh
                geometry={nodes.Object_38_GlassLights_0.geometry}
                material={materials.GlassLights}
              />
              <mesh
                geometry={nodes.Object_39_LightEmissiveWhite_0.geometry}
                material={materials.LightEmissiveWhite}
              />
            </group>
            <mesh
              geometry={nodes.Object_41_CARBONE_0.geometry}
              material={materials.CARBONE}
              position={[0, -0.496, 1.029]}
              rotation={[0.013, 0, -Math.PI]}
              scale={0.001}
            />
            <group
              position={[0, 0.135, -0.061]}
              rotation={[0.013, 0, -Math.PI]}
              scale={0.001}
            >
              <mesh
                geometry={nodes.Object_44_CARBONE_0.geometry}
                material={materials.CARBONE}
              />
              <mesh
                geometry={nodes.Object_45_Chrome_0.geometry}
                material={materials.Chrome}
              />
              <mesh
                geometry={nodes.Object_46_GLASS_0.geometry}
                material={materials.GLASS}
              />
            </group>
            <mesh
              geometry={nodes.Object_48_CARBONE_0.geometry}
              material={materials.CARBONE}
              position={[0, 0.135, -0.061]}
              rotation={[0.013, 0, -Math.PI]}
              scale={0.001}
            />
            <group
              position={[0, 0.135, -0.061]}
              rotation={[0.013, 0, -Math.PI]}
              scale={0.001}
            >
              <mesh
                geometry={nodes.Object_50_material_0_0.geometry}
                material={materials.material_0}
              />
              <mesh
                geometry={nodes.Object_52_Undercarriage_0.geometry}
                material={materials.Undercarriage}
              />
              <mesh
                geometry={nodes.Object_53_CARBONE_0.geometry}
                material={materials.CARBONE}
              />
              <mesh
                geometry={nodes.Object_53_Material003_0.geometry}
                material={materials["Material.003"]}
              />
              <mesh
                geometry={nodes.Object_54_CARBONE_0.geometry}
                material={materials.CARBONE}
              />
              <mesh
                geometry={nodes.Object_55_MetalDark_0.geometry}
                material={materials.MetalDark}
              />
              <mesh
                geometry={nodes.Object_56_Chrome_0.geometry}
                material={materials.Chrome}
              />
              <mesh
                geometry={nodes.Object_57_GlassLights_0.geometry}
                material={materials.GlassLights}
              />
              <mesh
                geometry={nodes.Object_58_Aluminum_0.geometry}
                material={materials.Aluminum}
              />
              <mesh
                geometry={nodes.Object_59_MetalExhaustTextured_0.geometry}
                material={materials.MetalExhaustTextured}
              />
              <mesh
                geometry={nodes.Object_60_intTexButtonsGlossy_0.geometry}
                material={materials.intTexButtonsGlossy}
              />
              <mesh
                geometry={nodes.Object_61_Material044_0.geometry}
                material={materials["Material.044"]}
              />
              <mesh
                geometry={nodes.Object_62_JANTE001_0.geometry}
                material={materials["JANTE.001"]}
              />
              <mesh
                geometry={nodes.Object_63_GLASS_0.geometry}
                material={materials.GLASS}
              />
              <mesh
                geometry={nodes.Object_53001_CARBONE_0.geometry}
                material={materials.CARBONE}
              />
            </group>
            <mesh
              geometry={nodes.Object_65_JANTE001_0.geometry}
              material={materials["JANTE.001"]}
              position={[0, 2.389, 0.391]}
              rotation={[0.913, 0, Math.PI / 2]}
              scale={2.597}
            />
            <mesh
              geometry={nodes.Object_67_CARBONE_0.geometry}
              material={materials.CARBONE}
              position={[0, 0.135, -0.061]}
              rotation={[-1.558, 0, -Math.PI]}
            />
          </group>
        </group>
        <mesh
          geometry={nodes.Cylinder01_Material002_0.geometry}
          material={materials["Material.002"]}
          position={[0, 63.895, 44.153]}
          scale={7.433}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/lambo.gltf");
